name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV

      - name: Building TCET Linux Welcome Tar file
        run: |
          ls -la
          cd ..
          ls -la
          tar -czf tcet-linux-set-once.tar.gz tcet-linux-set-once/
          touch checksum
          sha256sum tcet-linux-set-once.tar.gz > checksum
          mv checksum tcet-linux-set-once/
          mv tcet-linux-set-once.tar.gz tcet-linux-set-once/
          ls -la
          
      - name: Delete Previous Latest release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          github_token: ${{ secrets.PAT_TOKEN }}
          delete_release: true
          
      - name: Release Tar File with latest
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz,checksum"
          generateReleaseNotes: false
          name: "TCET-Linux-set-once"
          tag: latest
          
      - name: Release Tar File
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz,checksum"
          generateReleaseNotes: false
          name: "TCET-Linux-set-once"
          tag: ${{ env.DATE }}

      
